
Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "file", source: "source", destination: "/home/vagrant"
  config.vm.provision "shell", path: "provision/web-provision.sh"
  config.vm.network "forwarded_port", guest: 8081, host: 1234

  config.trigger.before :destroy, :halt, :package do |trigger|
    trigger.run_remote = {inline: "sudo netstat -lpn |grep :'8081'"}
    trigger.run_remote = {inline: "sudo pkill -f node"}
  end

end
